### ISSUE TITLE
Refresh doesn't remove items from file list.

### ISSUE THREAD

**Issue by simotek** [DaveMDS/egitu#2] opened 2015-07-22 22:48 UTC
1. Modify a file
2. Open egitu
3. Manually remove file modifications
4. Refesh egitu
5. File with no changes is still in the list.

Again pretty minor not a blocking issue

**Comment by DaveMDS** [comment] 2015-08-05 15:11
I cannot reproduce this issue here
can you double check that is broken for you? 
maybe you get some python errors on console when this occur?

**Comment by simotek** [comment] 2015-08-06 08:07
I can't replicate this today, maybe its the fault of a NFS server.

**Comment by DaveMDS** [comment] 2015-08-06 08:17
ok, then I'm closing this, please reopen if you see it again

**Closed as completed by DaveMDS** 2015-08-06 08:17 UTC
